name: chat_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.9.0
  shared_preferences: ^2.0.15
  firebase_core: ^2.9.0
  firebase_auth: ^4.2.2
  easy_localization: ^3.0.1
  google_nav_bar: ^5.0.6
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  cloud_firestore: ^4.5.0
  dio: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/rives/
    - assets/fonts/
    - assets/ca/
    - lib/resources/translations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 500

